export const OPPORTUNITY_TITLE_MIN_LENGTH = 3;
export const OPPORTUNITY_TITLE_MAX_LENGTH = 120;
export const OPPORTUNITY_DESCRIPTION_MIN_LENGTH = 10;
export const OPPORTUNITY_DESCRIPTION_MAX_LENGTH = 500;
