jwt.public.key=${env.JWT_PUBLIC_KEY}
jwt.private.key=${env.JWT_PRIVATE_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=${env.MAIL_PORT}
spring.mail.username=${env.MAIL_USERNAME}
spring.mail.password=${env.MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.name=weunite-api
spring.datasource.url=jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.DB_NAME:weunite}
spring.datasource.username=${env.DB_USERNAME}
spring.datasource.password=${env.DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
app.cors.allowed-origins=${env.CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.default-property-inclusion=non_null

cloudinary.url=${env.CLOUDINARY_URL}

# Cloudinary Image Height Standards
cloudinary.image.profile.height=400
cloudinary.image.banner.height=300
cloudinary.image.post.height=720
cloudinary.image.post.width=1280
cloudinary.image.post.vertical-max-height=500
cloudinary.image.post.vertical-max-width=375

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
