create table if not exists tb_role (
  id bigint generated by default as identity primary key,
  name varchar(50) not null unique
);

create table if not exists tb_user (
  id bigint generated by default as identity primary key,
  dtype varchar(31) not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone,
  name varchar(100) not null,
  username varchar(30) not null unique,
  email varchar(254) not null unique,
  password varchar(255) not null,
  email_verified boolean not null,
  verification_token varchar(255),
  verification_token_expires timestamp with time zone,
  is_banned boolean not null,
  is_suspended boolean not null,
  banned_at timestamp with time zone,
  banned_reason varchar(500),
  banned_by_admin_id bigint,
  suspended_until timestamp with time zone,
  suspension_reason varchar(500),
  is_private boolean not null,
  profile_img varchar(255),
  banner_img varchar(255),
  bio varchar(500),
  cpf varchar(255),
  height double precision,
  weight double precision,
  foot_domain varchar(255),
  position varchar(255),
  birth_date date,
  cnpj varchar(255)
);

create table if not exists tb_user_roles (
  user_id bigint not null references tb_user(id),
  role_id bigint not null references tb_role(id),
  primary key (user_id, role_id)
);

create table if not exists skill (
  id bigint generated by default as identity primary key,
  name varchar(255) not null unique
);

create table if not exists user_skills (
  user_id bigint not null references tb_user(id),
  skill_id bigint not null references skill(id),
  primary key (user_id, skill_id)
);

create table if not exists post (
  id bigint generated by default as identity primary key,
  user_id bigint not null references tb_user(id),
  text varchar(500),
  image_url varchar(500),
  deleted boolean not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone
);

create table if not exists comment (
  id bigint generated by default as identity primary key,
  user_id bigint not null references tb_user(id),
  post_id bigint not null references post(id),
  parent_id bigint references comment(id),
  text varchar(500),
  image_url varchar(500),
  deleted boolean not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone
);

create table if not exists tb_post_like (
  id bigint generated by default as identity primary key,
  post_id bigint references post(id),
  comment_id bigint references comment(id),
  user_id bigint not null references tb_user(id),
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone,
  unique (user_id, post_id),
  unique (user_id, comment_id)
);

create table if not exists tb_post_repost (
  id bigint generated by default as identity primary key,
  post_id bigint not null references post(id),
  user_id bigint not null references tb_user(id),
  created_at timestamp with time zone not null,
  unique (user_id, post_id)
);

create table if not exists opportunity (
  id bigint generated by default as identity primary key,
  company_id bigint not null references tb_user(id),
  title varchar(100) not null,
  description varchar(1000),
  location varchar(200),
  date_end date not null,
  deleted boolean not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone
);

create table if not exists opportunity_skills (
  opportunity_id bigint not null references opportunity(id),
  skills_id bigint not null references skill(id),
  primary key (opportunity_id, skills_id)
);

create table if not exists subscriber (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references tb_user(id),
  opportunity_id bigint not null references opportunity(id),
  unique (athlete_id, opportunity_id)
);

create table if not exists saved_opportunities (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references tb_user(id),
  opportunity_id bigint not null references opportunity(id),
  saved_at timestamp with time zone not null,
  unique (athlete_id, opportunity_id)
);

create table if not exists follow (
  id bigint generated by default as identity primary key,
  follower_id bigint not null references tb_user(id),
  followed_id bigint not null references tb_user(id),
  status varchar(255) not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone,
  unique (follower_id, followed_id)
);

create table if not exists tb_conversation (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone
);

create table if not exists tb_conversation_participants (
  conversation_id bigint not null references tb_conversation(id),
  user_id bigint not null references tb_user(id),
  primary key (conversation_id, user_id)
);

create table if not exists tb_message (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references tb_conversation(id),
  sender_id bigint not null references tb_user(id),
  content text not null,
  is_read boolean not null,
  created_at timestamp with time zone not null,
  read_at timestamp with time zone,
  type varchar(255) not null,
  deleted boolean not null,
  edited boolean not null,
  edited_at timestamp with time zone
);

create table if not exists user_presence (
  user_id bigint primary key,
  status varchar(20) not null,
  updated_at timestamp without time zone not null
);

create table if not exists tb_notification (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  type varchar(50) not null,
  actor_id bigint not null,
  actor_name varchar(255) not null,
  actor_username varchar(255) not null,
  actor_profile_img varchar(255),
  related_entity_id bigint not null,
  message varchar(500) not null,
  is_read boolean not null,
  created_at timestamp with time zone not null
);

create table if not exists report (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references tb_user(id),
  type varchar(255) not null,
  entity_id bigint not null,
  reason varchar(500),
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone,
  status varchar(255) not null,
  action_taken varchar(255) not null,
  resolved_at timestamp with time zone,
  resolved_by_admin_id bigint
);

insert into tb_role (name)
select 'BASIC'
where not exists (select 1 from tb_role where name = 'BASIC');

insert into tb_role (name)
select 'ADMIN'
where not exists (select 1 from tb_role where name = 'ADMIN');

insert into tb_role (name)
select 'COMPANY'
where not exists (select 1 from tb_role where name = 'COMPANY');

insert into tb_role (name)
select 'ATHLETE'
where not exists (select 1 from tb_role where name = 'ATHLETE');
